apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transform-processor-kafka
  labels:
    app: transform-processor-kafka
    type: stream-ats
    component: transform-processor-kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transform-processor-kafka
        type: acceptance-tests
        component: transform-processor-kafka
    spec:
      containers:
      - name: transform-processor
        image: springcloudstream/transform-processor-kafka:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
            value: kafka-zk:2181
          - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION
            value: http-out
          - name: SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION
            value: transformer-out
          - name: TRANSFORMER_EXPRESSION
            value: payload.toUpperCase()
          - name: LOGGING_FILE
            value: transform-processor-kafka.log
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: logfile,health,info
          - name: SPRING_CLOUD_STREAMAPP_SECURITY_ENABLED
            value: "false"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
