apiVersion: v1
kind: Service
metadata:
  name: transform-processor-kafka
  labels:
    app: transform-processor-kafka
    type: stream-ats
    component: transform-processor-kafka
    spring-deployment-id: transform-processor
spec:
  type: NodePort
  ports:
  - port: 80
    name: transform-processor-kafka-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: transform-processor-kafka 
    type: acceptance-tests
    component: transform-processor-kafka
