---
applications:
- name: partitioning-consumer2
  host: partitioning-consumer2
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: /tmp/partitioning-consumer-rabbit.jar
  env:
    SPRING_APPLICATION_JSON: '{"maven": { "remote-repositories": { "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } }'
    LOGGING_FILE: partconsumer2.log
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: logfile
    SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCEINDEX: 1
services:
- scst-rabbit