apiVersion: v1
kind: Service
metadata:
  name: partitioning-consumer3-sample-kafka
  labels:
    app: partitioning-consumer3-sample-kafka
    type: acceptance-tests
    component: partitioning-consumer3-sample-kafka
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: partitioning-consumer3-sample-kafka-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: partitioning-consumer3-sample-kafka 
    type: acceptance-tests
    component: partitioning-consumer3-sample-kafka
