apiVersion: apps/v1
kind: Deployment
metadata:
  name: partitioning-producer-sample-kafka
  labels:
    app: partitioning-producer-sample-kafka
    type: acceptance-tests
    component: partitioning-producer-sample-kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: partitioning-producer-sample-kafka
        type: acceptance-tests
        component: partitioning-producer-sample-kafka
    spec:
      containers:
      - name: partitioning-producer-sample
        image: springcloudstream/partitioning-producer-sample-kafka:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
            value: kafka-zk:2181
          - name: LOGGING_FILE
            value: partitioning-producer-sample-kafka.log
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: logfile,health,info
          - name: SPRING_CLOUD_STREAMAPP_SECURITY_ENABLED
            value: "false"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
