spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 3
        bindings:
          input:
            consumer:
              autoRebalanceEnabled: false
      bindings:
        input:
          destination: partitioned.destination
          group: myGroup
          consumer:
            partitioned: true
            instanceIndex: 0
            instanceCount: 3