spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 3
      bindings:
        input:
          destination: partitioned.destination
          group: myGroup