spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 3
      bindings:
        input:
          destination: partitioned.destination
          group: myGroup
          consumer:
            partitioned: true
            instanceIndex: 0
            instanceCount: 3
            autoRebalanceEnabled: false