apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log
  labels:
    app: log
    type: acceptance-tests
    component: log
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: log
        component: log 
    spec:
      containers:
      - name: log
        image: springcloudstream/log-sink-kafka:latest 
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
            value: kafka-zk:2181
          - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION
            value: foo
          - name: LOG_EXPRESSION
            value: "'TICKTOCK - TIMESTAMP: '.concat(payload)"
          - name: LOGGING_FILE
            value: log-sink.log
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: logfile,health,info
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
