apiVersion: v1
kind: Service
metadata:
  name: uppercase-transformer-kafka
  labels:
    app: uppercase-transformer-kafka
    type: acceptance-tests
    component: uppercase-transformer-kafka
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: uppercase-transformer-kafka-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: uppercase-transformer-kafka 
    type: acceptance-tests
    component: uppercase-transformer-kafka
